name: Scrape
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Run
        run: pipenv run python scrape.py

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git status
          git pull origin $GITHUB_REF
          git add ./
          git commit -m "Daily scrape" && git push || true
        shell: bash